### ISSUE TITLE
fc-match won't recognize material-wifi

### ISSUE THREAD

**Issue by ethanabrooks** [dcousens/material-wifi-icons#2]
So, I have material-wifi installed:

❯ fc-list | ag wifi
/usr/share/fonts/TTF/material-wifi.ttf: material\-wifi:style=Regular
but fc-match is just not working:

❯ fc-match material\-wifi                        
DejaVuSans.ttf: "DejaVu Sans" "Book"
❯ fc-match material-wifi                        
DejaVuSans.ttf: "DejaVu Sans" "Book"
Did you have to modify one of your font config files somehow?

**Comment by dcousens** [comment]
> $ fc-list | ag wifi
> /usr/share/fonts/material-wifi.ttf: material\-wifi:style=Regular

> $ fc-match "material\\-wifi"
> material-wifi.ttf: "material-wifi" "Regular"

Note the escaping `\`.
Closing in favour of https://github.com/dcousens/material-wifi-icons/issues/1

**Comment by ethanabrooks** [comment]
Ah. Thanks for the correction.
