### ISSUE TITLE
Integration wi-fi icons into the front-end

### ISSUE THREAD

**Issue by bsurai** [dcousens/material-wifi-icons#3]
Hi.
I can't understand how to integrate these icons into my front-end project. Usually I use css files and class names (like with font awesome). Could you advise me.

Thank you.

**Comment by dcousens** [comment]
``` bash
echo -e "\ue905\ue903\ue901\ue900"
```

You can use those codes individually in your CSS like you would with `font-awesome`.

``` css
.wifi-full:before { content: '\ue905'; }
```

**Comment by bsurai** [comment]
Hmm. I only see ue905 as result. I guess, browsers ans my Ubuntu don't understand this font (material-wifi.ttf). I tried to install the font on my box. Also I tried to load the font to html page. But something goes wrong.

I use:
- Ubuntu 16.04
- Chrome, Chromium, Firefox

**Comment by dcousens** [comment]
@bsurai apologies,  that first example was a bit lackluster (and wrong!).
Here is a working example for me on Chromium.

``` html
<html>
<style>
@font-face {
  font-family: 'wifi';
  src: url('./material-wifi.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
.wifi-full:before,
.wifi-most:before,
.wifi-half:before,
.wifi-none:before {
  display: inline-block;
  font-family: 'wifi';
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  text-rendering: auto;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
.wifi-full:before { content: '\e905'; }
.wifi-most:before { content: '\e903'; }
.wifi-half:before { content: '\e901'; }
.wifi-none:before { content: '\e900'; }
</style>
<body>
<i class="wifi-full"></i>
<i class="wifi-most"></i>
<i class="wifi-half"></i>
<i class="wifi-none"></i>
</body>
</html>
````

**Comment by dcousens** [comment]
If you are guaranteed to have the font "installed" on your system,  you can remove the `@font-face` block,  and instead use `font-family: 'material\-wifi';`.

Added the file in https://github.com/dcousens/material-wifi-icons/commit/4f175dc76dd0f46bf905d9e17b52a5d0f72c2891

**Comment by bsurai** [comment]
Thank you. It helps me much :)
One more thing. It looks like `full` and `none` are messed, `most` and `half` are messed too. I've fixed it for myself.

**Comment by dcousens** [comment]
@bsurai can you submit the pull request to fix that?

**Comment by bsurai** [comment]
Sorry. It looks like I don't have permission to do that.

**Comment by dcousens** [comment]
Pull requests don't need permission,  but no worries,  I fixed it in https://github.com/dcousens/material-wifi-icons/commit/e26ab78c48d412d3a46846efbb134db3b6399a62
